### ISSUE TITLE
CFB path separators aren't properly handled

### ISSUE THREAD

**Issue by tim-weis** [tim-weis/ovba#22]
PR #21 surfaced an issue with path separators as interpreted by the [`cfb`](https://crates.io/crates/cfb) crate, that isn't currently honored by this implementation.

@JanMarvin Could you verify that the update on the `feature/path_sep` branch works for you? The following entry in your *Cargo.toml* file should pull in the latest changes:

```toml
[dependencies]
ovba = { git = "https://github.com/tim-weis/ovba", branch = "feature/path_sep" }
```
